spring.application.name=Acolyte App
spring.profiles.active=${APP_PROFILE:test}
spring.jpa.show-sql=true

auth.jwt.token.secret=51c3544ac33a24b012ba69bf6349db78
auth.jwt.token.expiration-time=1
auth.jwt.token.expiration-time.refresh=8